### ISSUE TITLE
Intermittent MySQL timeouts

### ISSUE THREAD

**Issue by SysEngDan** [bitnami/bitnami-docker-reportserver#8]
**Intermittent MySQL timeouts**

I'm using the ReportServer Bitnami image and MariaDB image exactly as described in the readme (see docker-compose file below). While using this stack, I've configured a 2nd MySQL Datasource in the Administration panel. Doesn't matter which database I choose to "Test Connection", if there hasn't been any interaction with that respective database in the last 30 seconds, I get an error. Clicking "Test Connection" immediately after the error is successful. It seems almost as if the application produces an error before completely setting up the connection. Which would explain why clicking the "Test Connection" again immediately after the error is successful.

Furthermore, if I continuously click "Test Connection" every few seconds, it's 100% successful thereafter. If I wait 27 seconds, it's successful. If I wait 31 seconds, it produces an error.

```
version: '3'
services:
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - /san/services/reportserver/db:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_reportserver
      - MARIADB_DATABASE=bitnami_reportserver
    networks:
      - reportserver-overlay
  php:
    image: bitnami/reportserver:3
    depends_on:
      - mariadb
    volumes:
      - /san/services/reportserver/data:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REPORTSERVER_DATABASE_USER=bn_reportserver
      - REPORTSERVER_DATABASE_NAME=bitnami_reportserver
    networks:
      - reportserver-overlay
    deploy:
      replicas: 1
networks:
  reportserver-overlay:
    external: true
```

**Steps to reproduce the issue:**

1. Deploy ReportServer stack with Docker Swarm (`docker stack deploy reportserver -c /san/services/reportserver/docker-compose.yml`)
2. Visit web UI and login
3. Go to Administration > Datasources
4. Click on any MySQL datasource
5. Click "Test Connection" -> Observe error

![image](https://user-images.githubusercontent.com/11705408/123450235-8657f500-d5aa-11eb-826f-0e862b1acd3e.png)

Error output:
```
net.datenwerke.rs.core.service.reportmanager.exceptions.DatabaseConnectionException: Could not open connection to: jdbc:mysql://<hidden> with user: <hidden>. com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 461,083 milliseconds ago. The last packet sent successfully to the server was 461,097 mi<br>	at net.datenwerke.rs.base.service.datasources.transformers.database.Database2TableTransformer.transform(Database2TableTransformer.java:57)<br>	at net.datenwerke.rs.base.service.datasources.transformers.database.Database2TableTransformer.transform(Database2TableTransformer.java:1)<br>	at net.datenwerke.rs.base.service.datasources.transformers.DatasourceTransformationServiceImpl.transform(DatasourceTransformationServiceImpl.java:29)<br>	at net.datenwerke.rs.base.service.reportengines.table.SimpleDataSupplier.getData(SimpleDataSupplier.java:141)<br>	at net.datenwerke.rs.base.service.reportengines.table.SimpleDataSupplier.getData(SimpleDataSupplier.java:132)<br>	at net.datenwerke.rs.base.service.reportengines.table.SimpleDataSupplier.getData(SimpleDataSupplier.java:119)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl.testConnection(DatasourceTesterRPCServiceImpl.java:104)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2.CGLIB$testConnection$0(&lt;generated&gt;)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2$$FastClassByGuice$$a41853c5.invoke(&lt;generated&gt;)<br>	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)<br>	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:64)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)<br>	at net.datenwerke.security.service.security.aop.SecurityCheckInterceptor.invoke(SecurityCheckInterceptor.java:109)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)<br>	at net.datenwerke.gf.service.gwtstacktrace.CatchStacktraceInterceptor.invoke(CatchStacktraceInterceptor.java:38)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)<br>	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2.testConnection(&lt;generated&gt;)<br>	at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)<br>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br>	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)<br>	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2.CGLIB$processCall$4(&lt;generated&gt;)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2$$FastClassByGuice$$a41853c5.invoke(&lt;generated&gt;)<br>	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)<br>	at net.datenwerke.security.service.security.aop.SecurityCheckInterceptor.invoke(SecurityCheckInterceptor.java:109)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)<br>	at net.datenwerke.gf.service.gwtstacktrace.CatchStacktraceInterceptor.invoke(CatchStacktraceInterceptor.java:38)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)<br>	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2.processCall(&lt;generated&gt;)<br>	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2.CGLIB$processCall$3(&lt;generated&gt;)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2$$FastClassByGuice$$a41853c5.invoke(&lt;generated&gt;)<br>	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)<br>	at net.datenwerke.security.service.security.aop.SecurityCheckInterceptor.invoke(SecurityCheckInterceptor.java:109)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)<br>	at net.datenwerke.gf.service.gwtstacktrace.CatchStacktraceInterceptor.invoke(CatchStacktraceInterceptor.java:38)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)<br>	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2.processCall(&lt;generated&gt;)<br>	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)<br>	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)<br>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)<br>	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2.CGLIB$service$24(&lt;generated&gt;)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2$$FastClassByGuice$$a41853c5.invoke(&lt;generated&gt;)<br>	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:76)<br>	at net.datenwerke.security.service.security.aop.SecurityCheckInterceptor.invoke(SecurityCheckInterceptor.java:109)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)<br>	at net.datenwerke.gf.service.gwtstacktrace.CatchStacktraceInterceptor.invoke(CatchStacktraceInterceptor.java:38)<br>	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:78)<br>	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:54)<br>	at net.datenwerke.rs.adminutils.server.datasourcetester.DatasourceTesterRPCServiceImpl$$EnhancerByGuice$$88ce36c2.service(&lt;generated&gt;)<br>	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)<br>	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)<br>	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)<br>	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)<br>	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)<br>	at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:94)<br>	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)<br>	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)<br>	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)<br>	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)<br>	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)<br>	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)<br>	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)<br>	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)<br>	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)<br>	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)<br>	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)<br>	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)<br>	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)<br>	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)<br>	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)<br>	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)<br>	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)<br>	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)<br>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)<br>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)<br>	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br>	at java.base/java.lang.Thread.run(Thread.java:829)<br>Caused by: java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 461,083 milliseconds ago. The last packet sent successfully to the server was 461,097 milliseconds ago. is longer than the server configured value of &#39;wait_timeout&#39;. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property &#39;autoReconnect=true&#39; to avoid this problem.<br>	at net.datenwerke.dbpool.DbC3p0PoolServiceImpl$1.get(DbC3p0PoolServiceImpl.java:192)<br>	at net.datenwerke.dbpool.DbC3p0PoolServiceImpl$1.get(DbC3p0PoolServiceImpl.java:1)<br>	at net.datenwerke.rs.base.service.datasources.transformers.database.Database2TableTransformer.transform(Database2TableTransformer.java:54)<br>	... 86 more<br>Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 461,083 milliseconds ago. The last packet sent successfully to the server was 461,097 milliseconds ago. is longer than the server configured value of &#39;wait_timeout&#39;. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property &#39;autoReconnect=true&#39; to avoid this problem.<br>	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)<br>	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)<br>	at com.mysql.cj.jdbc.ConnectionImpl.setTransactionIsolation(ConnectionImpl.java:2266)<br>	at com.mchange.v2.c3p0.impl.NewProxyConnection.setTransactionIsolation(NewProxyConnection.java:835)<br>	at net.datenwerke.dbpool.DbC3p0PoolServiceImpl.configureConnection(DbC3p0PoolServiceImpl.java:289)<br>	at net.datenwerke.dbpool.DbC3p0PoolServiceImpl$1.get(DbC3p0PoolServiceImpl.java:166)<br>	... 88 more<br>Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 461,083 milliseconds ago. The last packet sent successfully to the server was 461,097 milliseconds ago. is longer than the server configured value of &#39;wait_timeout&#39;. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property &#39;autoReconnect=true&#39; to avoid this problem.<br>	at jdk.internal.reflect.GeneratedConstructorAccessor230.newInstance(Unknown Source)<br>	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br>	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)<br>	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)<br>	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)<br>	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)<br>	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)<br>	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:546)<br>	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:710)<br>	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:649)<br>	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:951)<br>	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:897)<br>	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073)<br>	at com.mysql.cj.jdbc.ConnectionImpl.setTransactionIsolation(ConnectionImpl.java:2261)<br>	... 91 more<br>Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.<br>	at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67)<br>	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)<br>	at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)<br>	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:52)<br>	at com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader(TimeTrackingPacketReader.java:41)<br>	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:54)<br>	at com.mysql.cj.protocol.a.MultiPacketReader.readHeader(MultiPacketReader.java:44)<br>	at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:540)<br>	... 97 more<br>
```

**Version**

Docker Version:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 16
  Running: 9
  Paused: 0
  Stopped: 7
 Images: 8
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 16cq8ut4ldpfdgqgr9dexi24a
  Is Manager: true
  ClusterID: vctmuphctbp9zqmb7b4bm8jj0
  Managers: 4
  Nodes: 4
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.30.230
  Manager Addresses:
   192.168.30.198:2377
   192.168.30.230:2377
   192.168.30.231:2377
   192.168.30.232:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.31.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.795GiB
 Name: d<hidden>
 ID: VYOP:U4NS:IFLY:PKRU:KB5O:BTLE:RYO6:7F3H:VZCB:WRP3:PDMR:DYL2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

** Environment Details **

This stack is running a local environment in my business which I own and operate.

**Comment by juan131** [comment]
Hi @SysEngDan 

Thanks so much for all the details! Honestly, it doesn't look to me like an issue in the image but some issue in the application (Reportserver) itself. Did you check in [Reportserver Forum](https://forum.reportserver.net/) if this issue was already reported?

> While using this stack, I've configured a 2nd MySQL Datasource in the Administration panel. Doesn't matter which database I choose to "Test Connection", if there hasn't been any interaction with that respective database in the last 30 seconds, I get an error

What second database did you use? Was it also a database running your Docker Swarm cluster?
